// Full Caribbean destinations database

export type Destination = {
  code: string;           // Airport/destination code
  name: string;
  country: string;
  flag: string;
  currencyCode: string;
  currencyName: string;
  peggedToUSD: boolean;
  region: "anglophone" | "french" | "dutch" | "spanish" | "other";
  popularFrom: string[];  // Origin countries with direct/popular routes
  description?: string;
};

export const destinations: Destination[] = [
  // ═══════════════════════════════════════════════════════════════════
  // ANGLOPHONE CARIBBEAN
  // ═══════════════════════════════════════════════════════════════════
  {
    code: "BGI",
    name: "Barbados",
    country: "Barbados",
    flag: "🇧🇧",
    currencyCode: "BBD",
    currencyName: "Barbadian Dollar",
    peggedToUSD: true,
    region: "anglophone",
    popularFrom: ["uk", "us", "canada"],
    description: "Little England of the Caribbean. Major hub for UK diaspora.",
  },
  {
    code: "KIN",
    name: "Jamaica",
    country: "Jamaica",
    flag: "🇯🇲",
    currencyCode: "JMD",
    currencyName: "Jamaican Dollar",
    peggedToUSD: false,
    region: "anglophone",
    popularFrom: ["uk", "us", "canada"],
    description: "Largest English-speaking Caribbean nation. Major tourism destination.",
  },
  {
    code: "POS",
    name: "Trinidad & Tobago",
    country: "Trinidad and Tobago",
    flag: "🇹🇹",
    currencyCode: "TTD",
    currencyName: "Trinidad & Tobago Dollar",
    peggedToUSD: false,
    region: "anglophone",
    popularFrom: ["uk", "us", "canada"],
    description: "Oil-rich twin islands. Home of Carnival and calypso.",
  },
  {
    code: "GEO",
    name: "Guyana",
    country: "Guyana",
    flag: "🇬🇾",
    currencyCode: "GYD",
    currencyName: "Guyanese Dollar",
    peggedToUSD: false,
    region: "anglophone",
    popularFrom: ["uk", "us", "canada"],
    description: "South American Caribbean. Growing economy with new oil discoveries.",
  },
  {
    code: "ANU",
    name: "Antigua",
    country: "Antigua and Barbuda",
    flag: "🇦🇬",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    peggedToUSD: true,
    region: "anglophone",
    popularFrom: ["uk", "us", "canada"],
    description: "365 beaches. Popular for sailing and luxury tourism.",
  },
  {
    code: "UVF",
    name: "St Lucia",
    country: "Saint Lucia",
    flag: "🇱🇨",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    peggedToUSD: true,
    region: "anglophone",
    popularFrom: ["uk", "us", "canada"],
    description: "The Pitons. Popular honeymoon and wedding destination.",
  },
  {
    code: "GND",
    name: "Grenada",
    country: "Grenada",
    flag: "🇬🇩",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    peggedToUSD: true,
    region: "anglophone",
    popularFrom: ["uk", "us", "canada"],
    description: "Spice Island. Known for nutmeg and pristine beaches.",
  },
  {
    code: "DOM",
    name: "Dominica",
    country: "Dominica",
    flag: "🇩🇲",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    peggedToUSD: true,
    region: "anglophone",
    popularFrom: ["uk", "us"],
    description: "Nature Island. Rainforests, waterfalls, eco-tourism.",
  },
  {
    code: "SVD",
    name: "St Vincent",
    country: "St Vincent and the Grenadines",
    flag: "🇻🇨",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    peggedToUSD: true,
    region: "anglophone",
    popularFrom: ["uk", "us"],
    description: "Grenadines islands. Sailing paradise.",
  },
  {
    code: "SKB",
    name: "St Kitts",
    country: "St Kitts and Nevis",
    flag: "🇰🇳",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    peggedToUSD: true,
    region: "anglophone",
    popularFrom: ["uk", "us"],
    description: "Sugar heritage. Citizenship by investment programme.",
  },
  {
    code: "NAS",
    name: "Bahamas",
    country: "The Bahamas",
    flag: "🇧🇸",
    currencyCode: "BSD",
    currencyName: "Bahamian Dollar",
    peggedToUSD: true,
    region: "anglophone",
    popularFrom: ["us", "uk", "canada"],
    description: "700 islands. Nassau, Paradise Island, Exumas.",
  },
  {
    code: "BZE",
    name: "Belize",
    country: "Belize",
    flag: "🇧🇿",
    currencyCode: "BZD",
    currencyName: "Belize Dollar",
    peggedToUSD: true,
    region: "anglophone",
    popularFrom: ["us"],
    description: "Central American Caribbean. Mayan ruins, barrier reef.",
  },
  {
    code: "BDA",
    name: "Bermuda",
    country: "Bermuda",
    flag: "🇧🇲",
    currencyCode: "BMD",
    currencyName: "Bermudian Dollar",
    peggedToUSD: true,
    region: "anglophone",
    popularFrom: ["uk", "us"],
    description: "North Atlantic. British territory, pink sand beaches.",
  },
  {
    code: "EIS",
    name: "British Virgin Islands",
    country: "British Virgin Islands",
    flag: "🇻🇬",
    currencyCode: "USD",
    currencyName: "US Dollar",
    peggedToUSD: true,
    region: "anglophone",
    popularFrom: ["uk", "us"],
    description: "Sailing capital. Tortola, Virgin Gorda.",
  },
  {
    code: "GCM",
    name: "Cayman Islands",
    country: "Cayman Islands",
    flag: "🇰🇾",
    currencyCode: "KYD",
    currencyName: "Cayman Islands Dollar",
    peggedToUSD: true,
    region: "anglophone",
    popularFrom: ["uk", "us"],
    description: "Financial centre. Seven Mile Beach, diving.",
  },
  {
    code: "PLS",
    name: "Turks & Caicos",
    country: "Turks and Caicos Islands",
    flag: "🇹🇨",
    currencyCode: "USD",
    currencyName: "US Dollar",
    peggedToUSD: true,
    region: "anglophone",
    popularFrom: ["us", "uk", "canada"],
    description: "Grace Bay Beach. Luxury resorts.",
  },
  {
    code: "AXA",
    name: "Anguilla",
    country: "Anguilla",
    flag: "🇦🇮",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    peggedToUSD: true,
    region: "anglophone",
    popularFrom: ["us", "uk"],
    description: "Luxury beach destination. 33 pristine beaches.",
  },
  {
    code: "MNI",
    name: "Montserrat",
    country: "Montserrat",
    flag: "🇲🇸",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    peggedToUSD: true,
    region: "anglophone",
    popularFrom: ["uk", "us"],
    description: "Emerald Isle of Caribbean. Active volcano, rebuilt after 1995 eruption.",
  },

  // ═══════════════════════════════════════════════════════════════════
  // FRENCH CARIBBEAN
  // ═══════════════════════════════════════════════════════════════════
  {
    code: "FDF",
    name: "Martinique",
    country: "Martinique",
    flag: "🇲🇶",
    currencyCode: "EUR",
    currencyName: "Euro",
    peggedToUSD: false,
    region: "french",
    popularFrom: ["france", "us", "canada"],
    description: "French overseas region. Rum, beaches, Mount Pelée.",
  },
  {
    code: "PTP",
    name: "Guadeloupe",
    country: "Guadeloupe",
    flag: "🇬🇵",
    currencyCode: "EUR",
    currencyName: "Euro",
    peggedToUSD: false,
    region: "french",
    popularFrom: ["france", "us", "canada"],
    description: "Butterfly-shaped islands. French Caribbean culture.",
  },
  {
    code: "SFG",
    name: "Saint Martin",
    country: "Saint Martin (French)",
    flag: "🇲🇫",
    currencyCode: "EUR",
    currencyName: "Euro",
    peggedToUSD: false,
    region: "french",
    popularFrom: ["france", "us", "netherlands"],
    description: "French side of shared island. Cuisine, beaches.",
  },
  {
    code: "SBH",
    name: "St Barthélemy",
    country: "Saint Barthélemy",
    flag: "🇧🇱",
    currencyCode: "EUR",
    currencyName: "Euro",
    peggedToUSD: false,
    region: "french",
    popularFrom: ["france", "us"],
    description: "Luxury island. Celebrity destination, high-end resorts.",
  },

  // ═══════════════════════════════════════════════════════════════════
  // DUTCH CARIBBEAN
  // ═══════════════════════════════════════════════════════════════════
  {
    code: "AUA",
    name: "Aruba",
    country: "Aruba",
    flag: "🇦🇼",
    currencyCode: "AWG",
    currencyName: "Aruban Florin",
    peggedToUSD: true,
    region: "dutch",
    popularFrom: ["netherlands", "us", "canada"],
    description: "One Happy Island. Desert climate, pristine beaches.",
  },
  {
    code: "CUR",
    name: "Curaçao",
    country: "Curaçao",
    flag: "🇨🇼",
    currencyCode: "ANG",
    currencyName: "Netherlands Antillean Guilder",
    peggedToUSD: true,
    region: "dutch",
    popularFrom: ["netherlands", "us"],
    description: "Willemstad's colourful architecture. Diving, culture.",
  },
  {
    code: "SXM",
    name: "Sint Maarten",
    country: "Sint Maarten (Dutch)",
    flag: "🇸🇽",
    currencyCode: "ANG",
    currencyName: "Netherlands Antillean Guilder",
    peggedToUSD: true,
    region: "dutch",
    popularFrom: ["netherlands", "us", "france"],
    description: "Dutch side of shared island. Maho Beach plane landings.",
  },
  {
    code: "BON",
    name: "Bonaire",
    country: "Bonaire",
    flag: "🇧🇶",
    currencyCode: "USD",
    currencyName: "US Dollar",
    peggedToUSD: true,
    region: "dutch",
    popularFrom: ["netherlands", "us"],
    description: "Divers' paradise. Special municipality of Netherlands.",
  },
  {
    code: "SAB",
    name: "Saba",
    country: "Saba",
    flag: "🇧🇶",
    currencyCode: "USD",
    currencyName: "US Dollar",
    peggedToUSD: true,
    region: "dutch",
    popularFrom: ["netherlands"],
    description: "Unspoiled nature. Hiking, diving. Smallest island.",
  },
  {
    code: "EUX",
    name: "Sint Eustatius",
    country: "Sint Eustatius",
    flag: "🇧🇶",
    currencyCode: "USD",
    currencyName: "US Dollar",
    peggedToUSD: true,
    region: "dutch",
    popularFrom: ["netherlands"],
    description: "Statia. Historic trading post, diving.",
  },

  // ═══════════════════════════════════════════════════════════════════
  // SPANISH CARIBBEAN
  // ═══════════════════════════════════════════════════════════════════
  {
    code: "SDQ",
    name: "Dominican Republic",
    country: "Dominican Republic",
    flag: "🇩🇴",
    currencyCode: "DOP",
    currencyName: "Dominican Peso",
    peggedToUSD: false,
    region: "spanish",
    popularFrom: ["us", "canada", "uk"],
    description: "Punta Cana, Santo Domingo. Largest Caribbean tourism.",
  },
  {
    code: "SJU",
    name: "Puerto Rico",
    country: "Puerto Rico",
    flag: "🇵🇷",
    currencyCode: "USD",
    currencyName: "US Dollar",
    peggedToUSD: true,
    region: "spanish",
    popularFrom: ["us"],
    description: "US territory. Old San Juan, El Yunque rainforest.",
  },
  {
    code: "HAV",
    name: "Cuba",
    country: "Cuba",
    flag: "🇨🇺",
    currencyCode: "CUP",
    currencyName: "Cuban Peso",
    peggedToUSD: false,
    region: "spanish",
    popularFrom: ["canada", "uk"],
    description: "Havana, classic cars. Restricted for US travellers.",
  },

  // ═══════════════════════════════════════════════════════════════════
  // OTHER
  // ═══════════════════════════════════════════════════════════════════
  {
    code: "PAP",
    name: "Haiti",
    country: "Haiti",
    flag: "🇭🇹",
    currencyCode: "HTG",
    currencyName: "Haitian Gourde",
    peggedToUSD: false,
    region: "other",
    popularFrom: ["us", "canada", "france"],
    description: "French Creole heritage. Citadelle Laferrière.",
  },
  {
    code: "STT",
    name: "US Virgin Islands",
    country: "US Virgin Islands",
    flag: "🇻🇮",
    currencyCode: "USD",
    currencyName: "US Dollar",
    peggedToUSD: true,
    region: "other",
    popularFrom: ["us"],
    description: "St Thomas, St Croix, St John. US territory.",
  },
  
  // ═══════════════════════════════════════════════════════════════════
  // ADDITIONAL TERRITORIES
  // ═══════════════════════════════════════════════════════════════════
  {
    code: "SLU",
    name: "St Lucia (Castries)",
    country: "Saint Lucia",
    flag: "🇱🇨",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    peggedToUSD: true,
    region: "anglophone",
    popularFrom: ["uk", "us", "canada"],
    description: "Alternative airport. George F.L. Charles Airport.",
  },
  {
    code: "TAB",
    name: "Tobago",
    country: "Trinidad and Tobago",
    flag: "🇹🇹",
    currencyCode: "TTD",
    currencyName: "Trinidad & Tobago Dollar",
    peggedToUSD: false,
    region: "anglophone",
    popularFrom: ["uk", "us", "canada"],
    description: "Sister island to Trinidad. Eco-tourism, beaches, diving.",
  },
  {
    code: "CIW",
    name: "Canouan",
    country: "St Vincent and the Grenadines",
    flag: "🇻🇨",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    peggedToUSD: true,
    region: "anglophone",
    popularFrom: ["us", "uk"],
    description: "Grenadines luxury island. Private resorts.",
  },
  {
    code: "BQU",
    name: "Bequia",
    country: "St Vincent and the Grenadines",
    flag: "🇻🇨",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    peggedToUSD: true,
    region: "anglophone",
    popularFrom: ["uk", "us"],
    description: "Largest Grenadine island. Sailing, whaling heritage.",
  },
  {
    code: "MUB",
    name: "Mustique",
    country: "St Vincent and the Grenadines",
    flag: "🇻🇨",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    peggedToUSD: true,
    region: "anglophone",
    popularFrom: ["uk", "us"],
    description: "Private island. Celebrity hideaway, ultra-luxury.",
  },
  {
    code: "UNI",
    name: "Union Island",
    country: "St Vincent and the Grenadines",
    flag: "🇻🇨",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    peggedToUSD: true,
    region: "anglophone",
    popularFrom: ["uk", "us"],
    description: "Gateway to Tobago Cays. Kitesurfing, sailing.",
  },
  {
    code: "CRU",
    name: "Carriacou",
    country: "Grenada",
    flag: "🇬🇩",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    peggedToUSD: true,
    region: "anglophone",
    popularFrom: ["uk", "us"],
    description: "Grenada's sister island. Boat building, sailing regattas.",
  },
  {
    code: "NEV",
    name: "Nevis",
    country: "St Kitts and Nevis",
    flag: "🇰🇳",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    peggedToUSD: true,
    region: "anglophone",
    popularFrom: ["uk", "us"],
    description: "Quieter sister to St Kitts. Birthplace of Alexander Hamilton.",
  },
  {
    code: "BBQ",
    name: "Barbuda",
    country: "Antigua and Barbuda",
    flag: "🇦🇬",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    peggedToUSD: true,
    region: "anglophone",
    popularFrom: ["uk", "us"],
    description: "Pink sand beaches. Frigate bird sanctuary. Princess Diana's favorite.",
  },
  
  // ═══════════════════════════════════════════════════════════════════
  // SURINAME (Dutch-speaking South America)
  // ═══════════════════════════════════════════════════════════════════
  {
    code: "PBM",
    name: "Suriname",
    country: "Suriname",
    flag: "🇸🇷",
    currencyCode: "SRD",
    currencyName: "Surinamese Dollar",
    peggedToUSD: false,
    region: "dutch",
    popularFrom: ["netherlands", "us"],
    description: "Dutch-speaking South America. Rainforests, colonial Paramaribo.",
  },
  
  // ═══════════════════════════════════════════════════════════════════
  // FRENCH GUIANA (South American Caribbean coast)
  // ═══════════════════════════════════════════════════════════════════
  {
    code: "CAY",
    name: "French Guiana",
    country: "French Guiana",
    flag: "🇬🇫",
    currencyCode: "EUR",
    currencyName: "Euro",
    peggedToUSD: false,
    region: "french",
    popularFrom: ["france"],
    description: "French overseas territory. Space centre, Amazon rainforest.",
  },
];

export function getDestination(code: string): Destination | undefined {
  return destinations.find(d => d.code === code);
}

export function getDestinationsByRegion(region: Destination["region"]): Destination[] {
  return destinations.filter(d => d.region === region);
}

export function getPopularDestinations(): Destination[] {
  // Return most popular ones for homepage display
  const popular = ["BGI", "KIN", "POS", "GEO", "ANU", "UVF", "AUA", "FDF"];
  return destinations.filter(d => popular.includes(d.code));
}

export function getDestinationsFrom(origin: string): Destination[] {
  return destinations.filter(d => d.popularFrom.includes(origin));
}

export function getAllDestinations(): Destination[] {
  return destinations;
}

export function getDestinationCount(): number {
  return destinations.length;
}
